[install]
# https://bun.sh/docs/runtime/bunfig#package-manager
exact = true
# ! IMPORTANT: Needed for docus to properly run dev/build
linker = "hoisted"
registry = { url = "https://registry.npmjs.org", token = "$NPM_TOKEN" }

[test]
# https://bun.sh/docs/runtime/bunfig#test-runner
coverage = true
coveragePathIgnorePatterns = [
  "**/dist/**",
  "**/tests/**",
  # TODO: Tests need to be added for get cli config
  "packages/cli/src/configs/get.ts",
  "packages/cli/src/utils/logs.ts"
]
coverageThreshold = 0.7